export const ACTION_NAME = {
    CHANGE_LOGIN: 'CHANGE_LOGIN',
    LOAD_IMAGES: 'LOAD_IMAGES',
    CHANGE_SELECTED_IMAGE_ID: 'CHANGE_SELECTED_IMAGE_ID',
    ADD_IMAGE: 'ADD_IMAGE',
    REMOVE_IMAGE: 'REMOVE_IMAGE',
    TOGGLE_LIKE: 'TOGGLE_LIKE',
};